package com.Accounting.app.config;

import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
public class ReceiptExtractionItemSchemaMigration implements ApplicationRunner {
    private final JdbcTemplate jdbcTemplate;

    public ReceiptExtractionItemSchemaMigration(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public void run(ApplicationArguments args) {
        if (!tableExists("receipt_extraction")) {
            return;
        }

        jdbcTemplate.execute(
                """
                create table if not exists receipt_extraction_item (
                    id integer generated by default as identity primary key,
                    name varchar(255),
                    amount numeric(19,2),
                    receipt_extraction_id integer references receipt_extraction(id)
                )
                """);
    }

    private boolean tableExists(String tableName) {
        Integer count = jdbcTemplate.queryForObject(
                """
                select count(*)
                from information_schema.tables
                where table_schema = current_schema()
                  and lower(table_name) = lower(?)
                """,
                Integer.class,
                tableName);

        return count != null && count > 0;
    }
}
